import numpy as np

def generate_ensemble(ANN_netcdf, parameter_list, ensemble_spread, ensemble_size):
    '''
    Receives neural network netcdf object, parameter_list to perturb,
    ensemble spread and ensemble size, and returns: 
    * numpy array of size num_of_parameters.sum() x ensemble_size
    * number of parameters of the same kind as a list num_of_parameters
    '''
    initial_ensemble = []
    num_of_parameters = []
    for parameter_key in parameter_list:
        parameter_vector = ANN_netcdf[parameter_key].values
        n_param = len(parameter_vector)
        if n_param > 5:
            parameter_scale = float(parameter_vector.std())
        else:
            parameter_scale = float(np.abs(parameter_vector).mean())

        random_perturbation = ensemble_spread * parameter_scale * np.random.randn(n_param, ensemble_size)

        ensemble = parameter_vector.reshape(-1,1) + random_perturbation
        initial_ensemble.append(ensemble)
        num_of_parameters.append(n_param)

    return np.concatenate(initial_ensemble), num_of_parameters

def parameter_vector_to_ANN(ANN_netcdf, parameter_list, num_of_parameters, parameter_vector):
    '''
    ANN_netcdf is unperturbed offline-trained ANN
    parameter_list is the list of parameters being perturbed
    num_of_parameters is the partition of parameter vector as it was done by function
    generate_ensemble
    parameter_vector is the vector generated by EKI
    '''
    ANN_modified = ANN_netcdf.copy()
    for j, parameter_key in enumerate(parameter_list):
        idx_start = sum(num_of_parameters[:j])
        idx_end = idx_start + num_of_parameters[j]
        ANN_modified[parameter_key].data = parameter_vector[idx_start:idx_end]

    return ANN_modified
