import numpy as np
import os
import sys

def generate_ensemble(ANN_netcdf, parameter_list, mom6_parameter_dict, ensemble_spread, ensemble_size, prior_cov_path, parameter_mask):
    '''
    Receives neural network netcdf object, parameter_list to perturb,
    ensemble spread and ensemble size, and returns: 
    * numpy array of size num_of_parameters.sum() x ensemble_size
    * number of parameters of the same kind as a list num_of_parameters
    '''
    num_of_parameters = []

    if not(os.path.exists(prior_cov_path)):
        print('Creating diagonal prior covariance matrix')
        initial_ensemble = []
        for parameter_key in parameter_list:
            parameter_vector = ANN_netcdf[parameter_key].values
            n_param = len(parameter_vector)

            if n_param > 5:
                parameter_scale = float(parameter_vector.std())
            else:
                parameter_scale = float(np.abs(parameter_vector).mean())

            random_perturbation = ensemble_spread * parameter_scale * np.random.randn(n_param, ensemble_size)
            if parameter_mask != 'None':
                random_perturbation = random_perturbation * np.array(parameter_mask[parameter_key]).reshape(-1,1)

            ensemble = parameter_vector.reshape(-1,1) + random_perturbation
            initial_ensemble.append(ensemble)
            num_of_parameters.append(n_param)
 
        for parameter_key in mom6_parameter_dict:
            mean = mom6_parameter_dict[parameter_key]['mean']
            std = mom6_parameter_dict[parameter_key]['std']
            ensemble = mean + std * np.random.randn(1, ensemble_size)
            initial_ensemble.append(ensemble)

        initial_ensemble = np.concatenate(initial_ensemble)
    else:
        print('Reading prior covariance matrix from the disk')
        if (len(mom6_parameter_dict.keys()) > 0):
            print('mom6 parameter dict is not yet tested with priors')
            sys.exit(0)

        C_xx_prior = np.load(prior_cov_path)
        random_perturbation = ensemble_spread * \
            np.random.multivariate_normal(
                mean=np.zeros(C_xx_prior.shape[0]),
                cov=C_xx_prior,
                size=ensemble_size
            ).T

        parameter_vector = []
        for parameter_key in parameter_list:
            x = ANN_netcdf[parameter_key].values
            num_of_parameters.append(len(x))
            parameter_vector.append(x)
        parameter_vector = np.concatenate(parameter_vector)
        initial_ensemble = parameter_vector.reshape(-1,1) + random_perturbation

    return initial_ensemble, num_of_parameters

def parameter_vector_to_ANN(ANN_netcdf, parameter_list, num_of_parameters, parameter_vector):
    '''
    ANN_netcdf is unperturbed offline-trained ANN
    parameter_list is the list of parameters being perturbed
    num_of_parameters is the partition of parameter vector as it was done by function
    generate_ensemble
    parameter_vector is the vector generated by EKI
    '''
    ANN_modified = ANN_netcdf.copy()
    for j, parameter_key in enumerate(parameter_list):
        idx_start = sum(num_of_parameters[:j])
        idx_end = idx_start + num_of_parameters[j]
        ANN_modified[parameter_key].data = parameter_vector[idx_start:idx_end]

    return ANN_modified

def save_params_txt(params, iteration_path):
    params_file = f'{iteration_path}-params.txt'

    if not(os.path.exists(params_file)):
        print('Saving parameters to file', params_file)
        np.savetxt(params_file, params)
    else:
        params_old = np.loadtxt(params_file)
        if not(np.allclose(params, params_old)):
            print('Parameters changed! Check the optimization algorithm.')
            sys.exit(1)   # terminate immediately with error code
        else:
            print('Parameters are the same. Keep going...')
